export let pintarPeliculas3 = [
    {
        nombre:"Las Horas",
        genero:"Ópera",
        duracion:2,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo1.png?alt=media&token=5cd5ee17-dd23-4b8f-a02f-4704d9092308",
        sinopsis:"Las horas, cuarta ópera del compositor estadounidense Kevin Puts, ganador del Premio Pulitzer de Música en el año 2012, nació gracias a una comisión conjunta del Met y la Orquesta de Filadelfia. La obra recibirá su estreno mundial durante la presente temporada de la compañía neoyorquina bajo la batuta de su director titular, Yannick Nézet-Séguin, que interpretará una partitura marcada por la vitalidad rítmica y estilos muy variados que transitan de la pasión violenta al más tierno lirismo.",
        clasificacion:"Contenido Alternativo",
        idioma: "Inglés",
        Director: "Phelim McDermott",
        Elenco:["Renée Fleming (Clarissa Vaughan)","Kelli O´Hara (Laura Brown)", "Kevin Hart","Joyce DiDonato (Virginia Woolf)."],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"10-Dic-2022"
    },
    {
        nombre:"Campeón",
        genero:"Ópera",
        duracion:3,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo2.png?alt=media&token=60fdb306-8d37-4eb8-9daf-b501272f7543",
        sinopsis:"En la temporada pasada, Terence Blachard, famoso músico de jazz fue el primer compositor de raza negra en presentar una ópera en la historia del Met, y el éxito fue rotundo.",
        clasificacion:"Contenido Alternativo",
        idioma: "Inglés",
        Director: "James Robinson",
        Elenco:["Latonia Moore (Emelda Griffith)" - "Ryan Speedo Green (el joven Emile Griffith)" - "Eric Owens (Emile Griffith)" - "Stephanie Blythe (Kathy Hagan)"],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"29-Abr-2023"
    },
    {
        nombre:"Lohengrin",
        genero:"Ópera",
        duracion:4,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo3.jpg?alt=media&token=6babf69e-a16d-410f-91ea-aee10855fb55",
        sinopsis:"Lohengrin, la quinta ópera de Wagner, nos adentra en los predios fantásticos de la mitología nórdica, en la que se da una convivencia de lo sobrenatural y lo humano, con todos los conflictos que afloran en el encuentro de esas dos esferas.",
        clasificacion:"Contenido Alternativo",
        idioma: "Alemán",
        Director: "François Girard",
        Elenco:["Tamara Wilson (Elsa)" - "Christine Goerke (Ortrud)" - "Eric Owens (Emile Griffith)" - "Stephanie Blythe (Kathy Hagan)"],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"18-Mar-2023"
    },
    {
        nombre:"El Caballero De La Rosa",
        genero:"Ópera",
        duracion:4,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo4.png?alt=media&token=84804222-e877-45d7-8e0d-5fc3a9e9dbb9",
        sinopsis:"Luego de componer los dramas intensos de Salomé y Electra, Strauss produjo, para sorpresa del público que esperaba otra ópera de tintes vanguardistas, una refinada comedia en el espíritu de Mozart con la complicidad de su libretista Hugo von Hofmannsthal.",
        clasificacion:"Contenido Alternativo",
        idioma: "Alemán",
        Director: "Robert Carsen",
        Elenco:["Lise Davidsen (Mariscala)" - " Isabel Leonard (Octavian)" - "Erin Morley (Sophie)" - "Markus Brück (Faninal"],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"15-Abr-2023"
    },
    {
        nombre:"La Flauta Mágica",
        genero:"Ópera",
        duracion:3,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo5.png?alt=media&token=b455443f-b2e4-4426-a2da-197101f177b0",
        sinopsis:"La flauta mágica fue el mayor éxito de la vida creativa de Mozart, pero vivió apenas unas pocas semanas para disfrutarlo porque una enfermedad repentina cobró su vida a los 35 años. Esta fábula atravesada por las fuerzas del bien y del mal y sazonada con elementos cómicos y solemnes tendrá una nueva producción escénica en el Met, a cargo del inglés Simon McBurney, que acude a numerosas proyecciones, efectos de sonido y acrobacias sobre las tablas.",
        clasificacion:"Contenido Alternativo",
        idioma: "Alemán",
        Director: "Simon McBurney",
        Elenco:["Erin Morley (Pamina)" - "Kathryn Lewek (Reina de la noche)" - "Lawrence Brownlee (Tamino)" - "Thomas Oliemans (Papageno)"],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"03-Jun-2023"
    },
    {
        nombre:"Don Giovanni",
        genero:"Ópera",
        duracion:2,
        poster:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/Alternativo6.png?alt=media&token=547e3951-98d9-4f2a-8c23-a67b262ccf1d",
        sinopsis:"En su segunda colaboración con el libretista Lorenzo da Ponte, Mozart creó una obra genial en la que cohabitan el drama y la comedia, la tendencia operística predilecta de finales del siglo XVIII. El legendario e infame seductor español, respaldado por un extenso inventario de mujeres burladas, será representado por el barítono, Peter Mattei, que al final se hunde en los infiernos como castigo a sus fechorías.",
        clasificacion:"Contenido Alternativo",
        idioma: "Italiano",
        Director: " Ivo van Hove",
        Elenco:["Federica Lombardi (Donna Anna)" - "Ana María Martínez (Donna Elvira)" - "Ying Fang (Zerlina)"],
        //Banner:"https://firebasestorage.googleapis.com/v0/b/cineayb.appspot.com/o/BannerMascotas-01.png?alt=media&token=b61f8ede-f372-4686-a22d-37241a98df75",
        Estreno:"20-May-2023"
    },
]